# =========================
# Production DB
# =========================
DB_URL = jdbc:oracle:thin:@//xx.xx.xx.xx:xxx/xxxx?useUnicode=true&characterEncoding=UTF-8
DB_USER_NAME = xxxxx
DB_PASSWORD = xxxxxx
DB_DRIVER_NAME = oracle.jdbc.OracleDriver

