# =========================
# UAT DB
# =========================
DB_URL = jdbc:oracle:thin:@//10.100.251.220:1522/mbsdev?useUnicode=true&characterEncoding=UTF-8
DB_USER_NAME = BOPMBS_OnBoarding
DB_PASSWORD = Bopnewmbs#1960
DB_DRIVER_NAME = oracle.jdbc.OracleDriver



authentication.validate.url=http://localhost:8080/AuthenticationAdminPortal/services/authentication/validate

logging.start.url=http://localhost:8080/loggingAdminPortal/services/logging/start
logging.finish.url=http://localhost:8080/loggingAdminPortal/services/logging/complete

http.connect.timeout.ms=5000
http.read.timeout.ms=10000


# HTTP timeouts
http.connect.timeout.ms=5000
http.connection.request.timeout.ms=5000
http.read.timeout.ms=10000

# Retry configuration
http.max.retries=1
http.initial.backoff.seconds=2

# Must be false in production
http.ssl.trust.all=false
